# Generated by Django 4.0.4 on 2022-05-22 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('talle', 'talle'), ('edicion', 'edicion')], max_length=100),
        ),
    ]
