# Generated by Django 4.0.4 on 2022-05-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Edicion', 'verbose_name_plural': 'Ediciones'},
        ),
    ]
