# Generated by Django 4.0.4 on 2022-05-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_options_alter_variation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterModelOptions(
            name='variation',
            options={},
        ),
    ]
