# Generated by Django 4.0.4 on 2022-05-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_iva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iva',
            options={'verbose_name': 'IVA', 'verbose_name_plural': 'IVA'},
        ),
        migrations.AlterField(
            model_name='iva',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
