# Generated by Django 4.0.4 on 2022-05-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_alter_iva_options_alter_iva_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iva',
            name='alicuota',
            field=models.FloatField(),
        ),
    ]
