# Generated by Django 4.0.4 on 2022-05-22 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_iva_alicuota'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IVA',
        ),
    ]
