# Generated by Django 4.0.4 on 2022-05-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_alter_cart_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={'verbose_name': 'Item - Pedido', 'verbose_name_plural': 'Items - Pedidos'},
        ),
        migrations.AlterModelTable(
            name='cart',
            table=None,
        ),
    ]
