# Generated by Django 4.0.4 on 2022-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria/Coleccion', 'verbose_name_plural': 'Categorias/Colecciones'},
        ),
    ]
