# Generated by Django 4.0.4 on 2022-05-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria - Coleccion', 'verbose_name_plural': 'Categorias - Colecciones'},
        ),
    ]
